spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/eze-item
    username: root
    password: P4ssw0rd
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8060

eureka:eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka