spring:
  application:
    name: eze-backend-spring
  datasource:
    url: jdbc:mysql://${EZE_BACKEND_MYSQL_SERVICE_URI:localhost}:3306/eze-database
    password: ${EZE_BACKEND_MYSQL_PASSWORD:P4ssw0rd}
    username: ${EZE_BACKEND_MYSQL_USERNAME:root}
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: ${EZE_BACKEND_SERVER_PORT:8080}

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

eze:
  secret-key: ${EZE_BACKEND_JWT_SECRET_KEY:somerandomstring}
  sadmin-username: ${EZE_BACKEND_SADMIN_USERNAME:sadmin}
  sadmin-password: ${EZE_BACKEND_SADMIN_PASSWORD:password}
  sadmin-email: ${EZE_BACKEND_SADMIN_EMAIL:glenneligio@gmail.com}