spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/eze-user
    username: root
    password: P4ssw0rd
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 8040
