spring:
  application:
    name: eze-backend-rest-api
  datasource:
    url: jdbc:mysql://localhost:3306/eze-database
    password: P4ssw0rd
    username: root
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8080