spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:mysql://localhost:3306/eze-transaction
    username: root
    password: P4ssw0rd
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true

server:
  port: 8020

eureka:eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
